### ISSUE TITLE
Error: 'faas' is the only valid provider for this tool - found: openfaas

### ISSUE THREAD

**Issue by alanjds** [alexellis/serverless-faas#14]
Trying to follow the [getting-started](https://github.com/openfaas/serverless-openfaas#getting-started) topic instructions, got errors:
```
'faas' is the only valid provider for this tool - found: openfaas
```

## Steps to Reproduce

1. `$ git clone https://github.com/openfaas/serverless-openfaas`
2. `$ ./prep.sh`
3. `$ ./test-plugin.sh`

## Your Environment
* serverless version: 1.27.2
* faas-cli version: 
  * Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
  * Version: 0.6.5
* docker version: 
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
* uname -a:
`Darwin gnpill.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64`
* Operating System and version: macOS Sierra (10.12)

**Comment by alexellis** [comment]
You need to use faas-cli from master. I think I mentioned this in the commit https://github.com/openfaas/serverless-openfaas/commit/a8bc82cb425a449a7897790c35a3a27fe8a37d29

```
git clone https://github.com/openfaas/faas-cli
cd faas-cli
./build_redist.sh
```

**Comment by alexellis** [comment]
There is a change [upstream](https://github.com/openfaas/faas-cli) to support "openfaas" as well as "faas" (for this plugin).

**Comment by burtonr** [comment]
Derek close
