### ISSUE TITLE
Proposal: Adopt XO as the official code style for the serveress plugin

### ISSUE THREAD

**Issue by austinfrey** [alexellis/serverless-faas#2]
XO provides linting and style help that is configurable. Could be useful to adopt a standard style for NodeJS code not just in this repo but any future NodeJS additions.

**Comment by alexellis** [comment]
Can you link to it? What are the pros and cons?

**Comment by austinfrey** [comment]
https://github.com/sindresorhus/xo

This would be the equivalent of using `gofmt` in the Go repos to enforce style and formatting.

Pros:
zero config, just use `xo --fix` and it will lint and format all code in the repo
standardizes style for all PR's
uses ESLint under the hood to provide linting
can easily be run alongside tests

cons:
the default style might not be the personal preference, but it is configurable if needed
another tool to learn

**Comment by austinfrey** [comment]
I'd like to revisit this. Having a standard format/code style will help eliminate a lot of noise in future PR's where spacing or tabs have changed but no real code changes took place, Being able to run `xo --fix` will help eliminate issues like that.
